name: C++ CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get build update && sudo apt-get install - build-essential

      - name: build the project using Makefile
        run: make
      
      - name: Run tests
        run: ./test/test